const rawData = {
"Ambientazione & Genere":{
"Dettaglio 1":[
"Aliena"
, "Anni 80"
, "Anni 90"
, "Antiche civiltà (Egitto, Grecia, Roma ecc)"
, "Antico Oriente"
, "Attuale/contemporanea"
, "Colonialismo"
, "Cyberpunk"
, "Fantascientifica"
, "Fantasy"
, "Horror"
, "Medievale"
, "Microbioma"
, "Mondo animale"
, "Mondo inanimato "
, "Preistoria"
, "Realtà virtuale"
, "Rinascimentale"
, "Rivoluzione francese"
, "Rivoluzione industriale"
, "Spazio (inteso come universo, cosmo)"
, "Steampunk (DiselPunk, BioPunk…)"
, "Western americana"
]
, "Dettaglio 2":[
, "All’interno di un social"
, "All’interno di un’astronave/viaggi spaziali"
, "Cappa e spada"
, "Città Orientali"
, "Civiltà perduta"
, "Comica "
, "Condizioni climatiche estreme"
, "Crisi (sociale, economica, ecc)"
, "Exopianeti"
, "Magia/sovrannaturale"
, "Natura incontaminata"
, "Noir"
, "Pandemia"
, "Pirati"
, "Post Apocalittica"
, "Pulp"
, "Regno degli dei"
, "Samurai"
, "Società segrete"
, "Sottomarina"
, "Surreale"
, "Survival zombie"
, "Zona di guerra"
]
}
,"Levitare":{
"Uno":[
"annullare"
, "cacciare"
, "conquistare"
, "controllare"
, "convertire/cambiare"
, "convincere"
, "curare"
, "distruggere"
, "guidare"
, "impedire"
, "ingannare"
, "inventare"
, "organizzare"
, "progettare"
, "proteggere"
, "riparare"
, "ritrovare"
, "rubare"
, "sabotare"
, "salvare"
, "sconfiggere"
, "scoprire"
, "terminare"
, "tradurre"
, "uccidere"
]
, "Due":[
"alleato/amico"
, "animale"
, "arma"
, "artefatto"
, "cospirazione"
, "cura"
, "erede"
, "guerra"
, "incantesimo"
, "libro"
, "malattia"
, "meccanismo"
, "nemico/traditore"
, "ordigno"
, "pergamena"
, "pianeta"
, "re/imperatore/reggente/presidente"
, "ribellione"
, "risorsa"
, "sistema"
, "superstite"
, "tesoro "
, "titolo"
, "trasporto"
, "veicolo"
        ]
        ,"Tre":[
"alieno"
, "benedetto"
, "complesso"
, "criptato"
, "dimenticato"
, "esplosivo"
, "fatale"
, "incontaminato"
, "innovativo"
, "leggendario"
, "magico"
, "maledetto"
, "mondiale"
, "pericoloso"
, "prezioso"
, "raro"
, "secolare"
, "segreto"
, "selvatico"
, "sepolto"
, "spaziale"
, "ultimo"
, "unico"
, "velenoso"
, "vitale"
        ]
    }
, "Domande":{
    "Pregi":[
, "Agile"
, "Altruista"
, "Amico fidato"
, "Amorevole"
, "Astuto"
, "Attento"
, "Ben organizzato"
, "Coraggioso"
, "Creativo oltre ogni limite"
, "Curioso "
, "Determinato"
, "Empatico"
, "Entusiasta"
, "Equilibrato"
, "Forzuto"
, "Generoso"
, "Intelligente"
, "Intuitivo"
, "Leale"
, "Memoria di ferro"
, "Mente matematica"
, "Ostinato"
, "Oratore nato"
, "Ottimista"
, "Ottimo udito"
, "Paziente"
, "Riflessivo"
, "Senso del dovere"
, "Sincero"
, "Vista acuta"
    ]
, "Difetti":[
, "Annoiato"
, "Antipatico"
, "Avido"
, "Bugiardo"
, "Codardo"
, "Contrario alle regole"
, "Credulone"
, "Distratto"
, "Egocentrico"
, "Egoista"
, "Gracile"
, "Impaziente"
, "Impressionabile"
, "Impulsivo"
, "Inaffidabile"
, "Irascibile"
, "Malato"
, "Materialista"
, "Memoria corta"
, "Molto diretto"
, "Pauroso/fobico"
, "Perditempo"
, "Permaloso"
, "Pessimista"
, "Poco malleabile"
, "Prende tutto alla lettera"
, "Rude"
, "Scapestrato"
, "Testa calda"
, "Troppo passionale"
, "Vendicativo"
]
,"Professione":[
"Alchimista"
, "Artigiano"
, "Cacciatore "
, "Cavaliere"
, "Contadino"
, "Esorcista"
, "Idraulico"
, "Impresario"
, "Killer"
, "Mago"
, "Manutentore"
, "Meccanico"
, "Operaio"
, "Pompiere"
, "Regista"
, "Regnante"
, "Scienziato"
, "Sovrintendente"
, "Studioso"
, "Torturatore"
, "Allevatore"
, "Artista"
, "Atleta"
, "Costruttore"
, "Ecclesiastico"
, "Esploratore"
, "Furfante"
, "Giornalista"
, "Guardia armata"
, "Impiegato"
, "Ingegnere"
, "Investigatore"
, "Insegnante"
, "Medico"
, "Pilota"
, "Presidente"
, "Sabotatore"
, "Scrittore"
, "Soldato"
, "Spia"
]
,"Luoghi/aggettivi":[
    
]
,"Relazioni":[
"Allievo"
, "Alter ego"
, "Amico"
, "Badante"
, "Capitano (o qualsiasi altro grado militare)"
, "Commilitone"
, "Compagno di cella"
, "Coniuge"
, "Copilota"
, "Domestico"
, "Familiare (specificare grado di parentela: fratello, sorella ecc.)"
, "Fidanzato/marito/moglie"
, "Guida"
, "Maestro"
, "Nemesi"
, "Nemico"
, "Supervisore"
, "Tutore "
, "Capo"
, "Carceriere"
, "Collega"
, "Compagno di scuola"
, "Compagno di squadra"
, "Confidente"
, "Consulente"
, "Guardia del corpo"
, "Idolo"
, "Istruttore"
, "Maggiordomo"
, "Navigatore"
, "Padrone"
, "Protettore"
, "Schiavo"
, "Seguace"
, "Sovrano"
, "Suddito"
, "Terapista"
]
}
}